version: "3.8"
services:
    db:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        container_name: db_snowtricks
        volumes: 
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_snowtricks
        depends_on:
            - db
        ports: 
            - 8761:80
        environment: 
            PMA_HOST: db
        networks:
            - dev

    maildev:
        image: maildev/maildev
        container_name: maildev_snowtricks
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports: 
            - 8751:80
        networks: 
            - dev

    www:
        build: php
        container_name: www_docker_symfony
        ports:
          - "8741:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        networks:
            - dev

networks:
    dev:

volumes: 
    db-data:
