version: "3.8"
services:
    db:
        image: mysql
        container_name: db_snowtricks
        restart: always
        ports:
          - 3306:3306
        volumes: 
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_snowtricks
        restart: always
        depends_on:
            - db
        ports: 
            - 8080:80
        environment: 
            PMA_HOST: db
        networks:
            - dev

    maildev:
        image: maildev/maildev
        container_name: maildev_snowtricks
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports: 
            - 8081:80
        restart: always
        networks: 
            - dev

networks:
    dev:

volumes: 
    db-data: