controllers:
    resource: ../../src/Controller/
    type: annotation

securityControllers:
    resource: ../../src/Security/Controller/
    type: annotation

tricksControllers:
    resource: ../../src/Tricks/Controller/
    type: annotation

mediaControllers:
    resource: ../../src/Media/Controller/
    type: annotation

cguControllers:
    resource: ../../src/CGU/Controller/
    type: annotation

commentsControllers:
    resource: ../../src/Comments/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
