controllers:
    resource: ../../src/Controller/
    type: annotation

security-controllers:
    resource: ../../src/Security/Controller/
    type: annotation

tricks-controllers:
    resource: ../../src/Tricks/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
